language: node_js #
node_js:
  - "node" #Use latest version of nodejs
branches:
  only: # Auto-deploy for branch master only
    - master
before_script: .travis/before_script.sh # Prepare the environment before running test and build.
script:
  - node set-env.ts
  - npm run build -- --prod
after_success:
 - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./.travis/after_success.sh; fi #Deploy after test and build success
