version: '3'
services:
  node:
    build: .
    ports:
     - 8081:3500
    volumes:
      - ./:/data
    links:
      - db
    depends_on:
      - db
    environment:
      VIRTUAL_HOST: api.blog.perso.local
  db:
    image: mysql:5.7
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: datauser
      MYSQL_PASSWORD: toto
      MYSQL_DATABASE: juleslaurentblogapi
