version: '3.8'
services:
  node:
    image: node:latest
    ports:
     - 8081:${SRV_PORT}
    volumes:
      - ./:/data
    links:
      - db
    depends_on:
      - db
    environment:
      VIRTUAL_HOST: api.blog.perso.local
    working_dir: /data
    command: sh docker-command.sh
  db:
    image: mysql:5.7
    ports:
      - ${DB_PORT}:3306
    volumes:
      - jlt-blog-api-data:/var/lib/mysql
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
volumes:
  jlt-blog-api-data: {}
